StoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            _cart = cartService;
        }

        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.CategoryRepository.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _manager.ProductService.GetAllProductsWithDetails(p);
            var pagination = new Pagination()
            {
                CurrenPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItems = _manager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            
            var model = _manager.ProductService.GetOneProduct(id, false);
            ViewData["Title"] = model?.ProductName;
            return View(model);
        }
    }
}

StoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <div class="lead text-center">
                    <i class="fa-solid fa-store text-secondary display-6"></i>
                    <br>
                    <div class="text-muted text-center my-2">
                        StoreApp
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-muted text-center my-2">
                    &copy; 2023, by Elif KAYMAK
                </div>
                <div class="text-center">
                    <div class="btn-group">
                        <a href="https://www.linkedin.com/in/elif-kaymak/" class="btn btn-outline-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a href="https://github.com/ElifCamliKaymak" class="btn btn-outline-secondary">
                            <i class="fa-brands fa-github"></i>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div products="" number="6"></div>
            </div>
        </div>
    </div>
</div>

StoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Commerce - @ViewData["Title"]</title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" />
</head>

<body>
    <header>
        <partial name="_Navbar" />
        @RenderSection("Header",false)
    </header>
    <div class="container">
        <main role="main" class=pb-3>
            @RenderBody()
        </main>
    </div>
    <footer>
        @RenderSection("Footer",false)
        <partial name="_Footer" />
    </footer>
    <script asp-append-version="true" src="~/lib/jquery/jquery.min.js"></script>
    <script asp-append-version="true" src="~/lib/bootstrap/js/bootstrap.bundle.js"></script>
    <script asp-append-version="true" src="~/lib/font-awesome/js/all.min.js"></script>
    <script asp-append-version="true" src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>

</html>

StoreApp/Views/Shared/_LoginMenu.cshtml
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li class="nav-item">
        <a class="nav-link" target="_blank" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
            <i class="fa-solid fa-code-compare"></i>
            Admin</a>
    </li>
}

@if (User.Identity.IsAuthenticated)
{

    <li class="nav-item">
        <a class="nav-link" asp-current="page" asp-area="" asp-controller="Account"
            asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Logout">
            <i class="fa-brands fa-space-awesome"></i>Logout</a>
    </li>
}
else
{
    <li class="nav-item">
        <a class="nav-link" asp-current="page" asp-area="" asp-controller="Account"
            asp-route-returnUrl="@Context.Request.PathAndQuery()" asp-action="Login">
            <i class="fa-regular fa-user"></i>
            Login</a>
    </li>
}

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar border-bottom bg-light navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <a class="navbar-brand" href="/">
            <i class="fa-solid fa-store fa-2x text-secondary"></i></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Product" asp-action="Index">Products
                            (@await Component.InvokeAsync("ProductSummary"))</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="Category" asp-action="Index">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-page="/Contact">Contact</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" asp-area="" asp-page="/Cart">
                            <i class="fa-solid fa-cart-shopping"></i>
                            Cart (@await Component.InvokeAsync("CartSummary"))
                        </a>
                    </li>  
                    <partial name="_LoginMenu"></partial>
                </ul>
            </div>
        </div>
    </div>
</nav>

StoreApp/Views/Shared/_Notification.cshtml
@if (TempData["info"] is not null)
{
    <div class="alert alert-info my-5" role="alert">
        @TempData["info"]
    </div>
}

@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-5" role="alert">
        @TempData["success"]
    </div>
}

@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-5" role="alert">
        @TempData["danger"]
    </div>
}

StoreApp/Views/Shared/_ProductCard.cshtml
@model Product


<div class="col-md-4 col-sm-12 col-xl-4 my-3">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.ProductName
        </div>

        <img src="@Model.ImageUrl" class="card-img-top" alt="...">
        <div class="card-body">
            <ul class="list-group list-group-flush text-center">
                <li class="list-group-item text-danger">@Model.Price.ToString("c")</li>
            </ul>
            <p class="card-text">@Model?.Summary</p>
        </div>
        <div class="card-body d-flex justify-content-center">
            <form id="@Model.ProductId" asp-page="/cart" method="post">
                <input type="hidden" asp-for="ProductId" />
                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                <button type="submit" class="btn btn-outline-secondary">
                    <i class="fa fa-cart-plus"></i>
                </button>
            </form>
            <div class="btn-group">
                <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.ProductId"
                    class="btn btn-outline-secondary rounded-2 mx-1">
                    <i class="fa-solid fa-arrow-right"></i>
                </a>
            </div>
        </div>
    </div>
</div>